#!/bin/bash

if [ $# != 2 ]; then
  echo 'Usage: clang-build-x64 <LD name> <AR name>'
  exit
fi

export CXXFLAGS=${CXXFLAGS}\ "-integrated-as -target x86_64-pc-none-elf64"
export CFLAGS=${CFLAGS}\ "-integrated-as -target x86_64-pc-none-elf64"
export LD=$1
export AR=$2

make clean
make kernel/build/kernel
